name: Bug Report
description: "For reporting either bugs or crashes"
labels:
  - S-needs-triage
body:
  - type: markdown
    attributes:
      value: >- 
        Before opening an issue, please make sure you have done the following:

        - **Have you read the [list of known issues](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility)?** Most problems
        (such as poor performance) are caused by out-of-date or incompatible graphics drivers.
        
        - **Have you used the [search tool](https://github.com/CaffeineMC/sodium-fabric/issues) to see if someone has already
        reported this problem?** If there is already an issue which describes your problem exactly, you should prefer to
        add information to that issue, rather than open a new one.
        
        - **Have you ensured that all of your mods (including Sodium) are up-to-date?** The latest version of Sodium
        can always be found [on Modrinth](https://modrinth.com/mod/sodium).
        
        - **If the issue occurs only with other mods installed, have you determined which mods exactly are causing the problem?** Please do not
        provide your entire mod list and expect us to be able to find which mods are causing the problem. You may try using
        a _binary search_ (also known as "divide and conquer") to figure out which mods are problematic.
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >-
        Use this section to describe the issue you are experiencing in as much depth as possible. The description should
        explain what behavior you were expecting, and why you believe the issue to be a bug. If the issue you are reporting
        only occurs with specific mods installed, then provide the name and version of each mod.

        **Hint:** If you have any screenshots, videos, or other information that you feel is necessary to
        explain the issue, you can attach them here.
  - type: textarea
    id: description-reproduction-steps
    attributes:
      label: Reproduction Steps
      description: >-
        Provide as much information as possible on how to reproduce this bug. Make sure your instructions are as clear and
        concise as possible, because other people will need to be able to follow your guide in order to re-create the issue.
        
        **Hint:**  A common way to fill this section out is to write a step-by-step guide.
    validations:
      required: true
  - type: textarea
    id: log-file
    attributes:
      label: Log File
      description: >-
        Attach the most recent log file from your client (`logs/latest.log`). This file should always be present.

        **Important:** Upload the file to this issue as an attachment by first selecting the text box below and then dragging your file onto it.
        GitHub will upload the file as an attachment and generate a link to it. This issue will be automatically closed if you omit a log
        file or copy-paste its content here.
      placeholder: >-
        Upload the log file here...
    validations:
      required: true
  - type: textarea
    id: crash-report-file
    attributes:
      label: Crash Report
      description: >-
        Attach the most recent crash report from the `crash-reports` folder in the same manner as before. This is different from the log file above, and it contains
        important information about your hardware and software configuration.
                
        **Important:** If your game is not crashing as a result of your problem, then you need to obtain a crash report manually. This can be done
        by loading the game to the main menu, and holding the F3+C keys together for approximately 10 seconds.
      placeholder: >-
        Upload the crash report file here...
    validations:
      required: true
